-- Exported schema from old Supabase project

CREATE TABLE IF NOT EXISTS "leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "motorcycle_id" uuid, "name" text NOT NULL, "phone" text NOT NULL, "source" text, "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()));

CREATE TABLE IF NOT EXISTS "motorcycles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "store_id" uuid NOT NULL, "make" text NOT NULL, "model" text NOT NULL, "year" integer NOT NULL, "price" numeric NOT NULL, "images" _text DEFAULT '{}'::text[], "status" text DEFAULT 'available'::text, "mileage" integer DEFAULT 0, "color" text, "slug" text, "description" text, "features" _text DEFAULT '{}'::text[], "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()), "condition" text DEFAULT 'Seminova'::text, "has_warranty" boolean DEFAULT false, "is_featured" boolean DEFAULT false);

CREATE TABLE IF NOT EXISTS "profiles" ("id" uuid NOT NULL, "store_id" uuid, "role" text DEFAULT 'admin'::text, "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()));

CREATE TABLE IF NOT EXISTS "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" text NOT NULL, "name" text NOT NULL, "logo_url" text, "primary_color" text DEFAULT '#4f46e5'::text, "secondary_color" text DEFAULT '#4f46e5'::text, "tertiary_color" text DEFAULT '#ffffff'::text, "whatsapp" text, "address" text, "is_dark_mode" boolean DEFAULT true, "show_financing" boolean DEFAULT true, "hero_title" text, "hero_subtitle" text, "hero_image" text, "about_text" text, "about_subtitle" text, "about_image" text, "about_paragraphs" _text DEFAULT '{}'::text[], "our_values" _text DEFAULT '{}'::text[], "financing_text" text, "email" text, "instagram" text, "facebook" text, "map_url" text, "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()), "whatsapp_message" text DEFAULT 'Olá! Tenho interesse em uma moto.'::text, "navbar_cta" text DEFAULT 'Premium Motorcycle Marketplace'::text, "whatsapp_number" text, "owner_id" uuid, "financing_title" text, "financing_subtitle" text, "financing_hero_image" text, "financing_main_title" text, "financing_secondary_image" text, "contact_title" text, "contact_subtitle" text, "address_title" text, "address_description" text, "channels_title" text, "channels_description" text, "hours_title" text, "hours_description" text, "hours_weekdays" text, "hours_saturday" text, "feature1_title" text, "feature1_desc" text, "feature2_title" text, "feature2_desc" text, "feature3_title" text, "feature3_desc" text, "featured_title" text, "about_teaser_title" text, "about_teaser_text" text);

